name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: codegen
        run: npm run codegen
      - name: build
        run: npm run build


      - name: Checkout private action repo
        uses: actions/checkout@v4
        with:
          repository: goldsky-io/goldsky-deploy
          path: .github/actions/goldsky-deploy

      - name: Run custom action
        uses: ./.github/actions/goldsky-deploy
        with:
          api_key: ${{ secrets.GOLDSKY_API_KEY }}
          subgraph_name: "ethereum-blocks"
          path: "."
